### ISSUE TITLE
Update to version 3.7.1 of protobuf

### ISSUE THREAD

**Issue by sjdrc** [hunter-packages/protobuf#10]
Hi, I've pulled the latest upstream sources into my repo here https://github.com/black-ai/protobuf/tree/hunter-3.7.1.

Everything compiles properly and seems to be fine.

Can you please update this in hunter?

**Comment by ruslo** [comment]
I've created branch `hunter-3.7.1`, please send patches there.

**Comment by ruslo** [comment]
For reference, patches for previous version 3.6.1.3 version:
- https://github.com/hunter-packages/protobuf/commits/hunter-3.6.1.3

**Comment by sjdrc** [comment]
https://github.com/hunter-packages/protobuf/pull/11
